package Common;

import java.util.*;


/**
 * Collector is a utility class to collect key value pairs
 * generated by user mapper/reducer classes. It is able to
 * the collected pairs according to key.
 *
 * @author      Rui Zhang
 * @author      Jing Gao
 * @version     1.0, 11/12/2013
 * @since       1.0
 */
public class Collector {

    
    public SortedMap<Object, ArrayList<Object>> collection=new TreeMap<Object, ArrayList<Object>>();
    
    /**
     * constructor of DataNode class
     *
     * @since           1.0
     */
    public Collector()
    {
        
    }
    
    /**
     * add list of kv pairs to collection, record unique keys
     *
     * @param kvPairs       the list of kv pairs
     * @since               1.0
     */
    public void addkvPairs(SortedMap<Object, ArrayList<Object>> kvPairs){
        collection.putAll(kvPairs);

    }

    /**
     * add a kv pair of object to collection
     *
     * @param key       the object key in the pair
     * @since           the object value in the pair
     */
    public void collect(Object key, Object value) {
        
        if(collection.containsKey(key)) {
            collection.get(key).add(value);
        } else {
            ArrayList<Object> obj = new ArrayList<Object>();
            obj.add(value);
            collection.put(key, obj);
        }

    }
    

}
